repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: pretty-format-json
        args: [ '--autofix','--indent=4','--no-sort-keys', '--no-ensure-ascii' ]
        files: \.json$

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit-security-scan

  - repo: local
    hooks:
      - id: commit-msg-lint
        name: Commit Message Linter
        entry: python3 validate_commit_message.py
        language: system
        stages: [ commit-msg ]
